[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "thalassa"
version = "0.2.0"
description = "Visualization of large scale results of hydrodynamic simulations"
authors = [
  "Panos Mavrogiorgos <pmav99@gmail.com>",
  "George Breyiannis <George.BREYIANNIS@ec.europa.eu>",
]
readme = "README.md"
homepage = "https://github.com/brey/Thalassa"
keywords = [
    "Hydrodynamic",
    "Sea",
    "Simulation",
    "Visualization",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    'License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)',
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    #'Operating System :: OS Independent',
    "Programming Language :: Python :: 3",
    'Topic :: Scientific/Engineering :: Atmospheric Science',
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Visualization",
]

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
pyproj = "^3.0"
holoviews = "^1.14"
numpy = "^1.20"
pandas = "^1.1"
bokeh = "^2.2"
panel = "^0.13.0a9"
xarray = "^0.19"
netCDF4 = "^1.5"
datashader = "^0.13"
ruyaml = "^0.20.0"
geoviews = "^1.9.2"
Cartopy = "<0.20"  # due to https://github.com/holoviz/geoviews/issues/529
Shapely = "<1.8"

[tool.poetry.group.dev.dependencies]
black = "^21.9b0"
jupyterlab = "^3.1"
nodeenv = "^1.6"
pyviz-comms = "^2.1"
mypy = "^0.910"
prospector = "^1.5"
pre-commit = "^2.15.0"
pyinstrument = "^4.0.4"


[tool.poetry.group.vim]
optional = true

[tool.poetry.group.vim.dependencies]
jupyterlab-vim = "^0.14"

[tool.poetry.group.panos.dependencies]
jupyterlab-nvdashboard = "^0.6.0"

[tool.black]
line-length = 109
target-version = ['py39']

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
implicit_reexport = true
strict = true
